CREATE TABLE DISCIPLINA 
( 
 nome_disciplina VARCHAR(50) PRIMARY KEY,  
 turma VARCHAR(50),  
 nome_sigla VARCHAR(50),
 idALUNO INT,
 idCURSO VARCHAR(50),
 idPROFESSOR INT,
 FOREIGN KEY (idALUNO) REFERENCES ALUNO(matricula_aluno)
 FOREIGN KEY (idCURSO) REFERENCES CURSO(nome_curso)
 FOREIGN KEY (idPROFESSOR) REFERENCES PROFESSOR(matricula_func)
)